Update Molecule to 5.0
Ableton/ansible-role-amtool pull request #131
Opened 2023-05-02 06:08 UTC by nre-ableton

Molecule 5.0 now requires the molecule-plugins[docker] package. The molecule-docker package is deprecated and its GitHub page has been archived.

2023-05-02 08:41 UTC, anz-ableton requested changes

2023-05-02 08:41 UTC, anz-ableton commented on requirements-dev.txt
> +    #   molecule
The update of `requirements-dev.txt` should be in a separate commit.

2023-05-02 08:58 UTC, nre-ableton commented on requirements-dev.txt
> +    #   molecule
Customarily we update both requirement files in one commit.

2023-05-02 10:15 UTC, ala-ableton commented on requirements-dev.txt
> +    #   molecule
When adding or removing a package to/from `requirements-dev.in`, it's fine to update `requirements-dev.txt` in a separate commit, but here it makes little sense, since the focus is on bumping the versions in `requirements-dev.txt`.

2023-05-03 08:19 UTC, anz-ableton commented on requirements-dev.txt
> +    #   molecule
But the contents of `requirements-dev.txt` are machine generated, and thus should be in a commit that follows our machine-generated-commit pattern.

2023-05-03 08:22 UTC, nre-ableton commented on requirements-dev.txt
> +    #   molecule
I can make this more explicit in the commit message if you'd prefer.

2023-05-03 08:57 UTC, nre-ableton commented on requirements-dev.txt
> +    #   molecule
Ok, so is this commit fine, then?

2023-05-03 09:12 UTC, anz-ableton approved these changes
LGTM.

2023-05-03 09:12 UTC, anz-ableton commented on requirements-dev.txt
> +    #   molecule
Yes, fine for me.  Approved.

2023-05-03 09:17 UTC, nre-ableton commented on requirements-dev.txt
> +    #   molecule
Ok, thanks!

2023-05-03 09:17 UTC, merged